### PR TITLE
[App] Order Dialog Function

### PR DESCRIPTION
**Pull request by aniku777tw**
與這支 PR 有關聯的 Otispm卡片:

URL: can't login Otispm 

# Description

Order Dialog Function and HTTP error handle.

# Step by Step

1. The app can **catch error after HTTP request** like 401 , timeout ...,etc.
2. In addition,when the app encounter response error it will show up a dialog .
3. The store name will show on App bar and the drawer.
4. Now we can connect with **NEW API : product** .
5. In the current demo , the **Product Cards'** data is from the dev server.  
6. In the **Order Dialog** , now it can add tags for each order .
7. In the **Order Dialog** , when the tag is not the format we wanted ,it will show up a snack bar and block the input.
8. In the **Order Dialog** ,the tag is on a scroll view , so it can contain more than 12 tags .
9. Watch the Demo video get more detail.

# Screenshot or more (Optional)

video:https://drive.google.com/drive/folders/1KxLV75lGIVRBG9bu4fe_zny577kyRbCm?usp=sharing

1.The catch error
image
image
2.order dialog
image

-----------------

提交 PR 前，請先檢查以下是否已完成：

* [X] 該分支是從最新 `master` 切出來 (如果不是，請先 rebase/merge 它)
* [x] 是否新增測試，或被現有的測試覆蓋
* [X] 這支 PR 是否有明確的標題、內容描述

-----------------

補充說明:

### CODE REVIEW

**Comment by Milesfeng** [comment]
drone.yml是舊的 , 重拉一下dev的

**Comment by aniku777tw** [comment]
> drone.yml是舊的 , 重拉一下dev的

OK I will pull dev next commit

**Comment by p0937507934** [comment]
@qaz10102030

**Comment by qaz10102030** [comment]
LGTM for Flutter parts.

**Pull request merged**
